[workspace]
members = ["./", "./macros"]

[package]
name = "staticpedia"
version = "0.1.0"
edition = "2018"

[dependencies]
url = "2.1.1"
percent-encoding = "2.1.0"
anyhow = "1.0.31"
thiserror = "1.0.19"
