[package]
name = "staticpedia-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.34"

[dependencies.syn]
version = "1.0.82"
features = ["derive", "parsing", "printing", "clone-impls", "extra-traits", "proc-macro"]
